export default {
	CHANGE_CATE_LIST:"CHANGE_CATE_LIST",
	// 选中的IDcateActiveId CHANGE
	CAHANGE_CATE_ACTIVE_ID:"CAHANGE_CATE_ACTIVE_ID",
	// 商品导航 kingKongList
	CHANGE_KINGKONG_LIST:"CHANGE_KINGKONG_LIST",
	// 首页商品列表categoryModule
	CAHNGE_CATEGORY_MODDULE:"CAHNGE_CATEGORY_MODDULE"
}

// export const CHANGE_FOUCS_LIST="CHANGE_FOUCS_LIST"